import { supabase } from './supabase.js'; import { loadHeader, $, getCart, saveCart, money, escapeHtml, getSettings } from './common.js';
await loadHeader(); const cart=getCart(), form=$('#checkout-form'), summary=$('#checkout-summary'), msg=$('#checkout-message');
if(!cart.length){location.href='carrito.html';throw new Error('empty cart');}
const settings=await getSettings().catch(()=>null); const delivery=$('#delivery'), addressFields=$('#address-fields');
if(settings){if(settings.delivery_enabled===false){delivery.value='pickup';[...delivery.options].find(o=>o.value==='delivery')?.remove();} if(settings.city)$('#city').value=settings.city;}
function render(){summary.innerHTML=`<h2>Tu pedido</h2><div class="order-items">${cart.map(i=>`<div class="order-item"><span>${escapeHtml(i.name)} × ${i.quantity}</span><strong>—</strong></div>`).join('')}</div><hr><p class="muted">El total definitivo será calculado y validado por Supabase al confirmar el pedido.</p>`;}
function toggle(){addressFields.hidden=delivery.value!=='delivery';} delivery.addEventListener('change',toggle);toggle();render();
form.addEventListener('submit',async e=>{e.preventDefault();msg.textContent='Validando inventario y creando pedido…';const fd=new FormData(form);const items=cart.map(i=>({product_id:i.product_id,variant_id:i.variant_id,quantity:i.quantity}));const payload={customer_name:String(fd.get('name')).trim(),customer_phone:String(fd.get('phone')).trim(),delivery_type:fd.get('delivery'),address:String(fd.get('address')||'').trim()||null,neighborhood:String(fd.get('neighborhood')||'').trim()||null,city:String(fd.get('city')||'').trim()||null,notes:String(fd.get('notes')||'').trim()||null,items};const {data,error}=await supabase.rpc('create_order', {p_order:payload});if(error){msg.textContent=error.message;return;}saveCart([]); const orderId=data?.order_id||data; let text=`Hola, quiero confirmar mi pedido en CAPRICHO STORE.\n\nPedido: ${orderId}\nCliente: ${payload.customer_name}\nTeléfono: ${payload.customer_phone}\nEntrega: ${payload.delivery_type==='delivery'?'Domicilio':'Recogida'}\n`;if(payload.delivery_type==='delivery')text+=`Dirección: ${payload.address||'—'}\nBarrio: ${payload.neighborhood||'—'}\nCiudad: ${payload.city||'—'}\n`;text+=`Notas: ${payload.notes||'—'}`;if(settings?.whatsapp){const digits=String(settings.whatsapp).replace(/\D/g,'');location.href=`https://wa.me/${digits}?text=${encodeURIComponent(text)}`;}else{msg.textContent='Pedido creado. WhatsApp todavía no ha sido configurado por la administradora.';}}
);
